# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gaWlhG1HzNc3enAQxMGU57i_2SkLPVy
"""

from sklearn.ensemble import RandomForestClassifier
rfr1 = RandomForestClassifier().fit(x_os,y_os.values.ravel())
y_pred = rfr1.predict(x_test_os)
rfr1 = RandomForestClassifier()
rfr1.fit(x_os,y_os.values.ravel())

y_pred = rfr1.predict(x_test_os)

print(classification_report(y_test_os,y_pred))

from xgbost import XGBClassifier
xgb1 =XGBClassifier()
xgb1.fit(x_os,y_os)

print(classification_report(y_test_os,y_pred))

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report

sv= SVC()

sv.fit(x_bal,y_bal)
y_pred = sv.predict(x_test_bal)
print(classification_report(y_test_bal,y_pred))

model = Sequential()
model.add(Dense(units = 128,activation='relu',input_shaped=(10,)))
model.add(Dense(units =128,activation='relu', kernel_initializer='random_uniform'))
model.add(Dropout(0.2))
model.add(Dense(units =256, activation='relu', kernel_initializer='random_uniform'))
model.add(Dropout(0.2))
model.add(Dense(units=128, activation='relu',kernel_initializer='random_uniform'))

model.add(Dense(units =1,activation+'sigmoid'))
model.summary()

rfr1.predict([[0,0,0,0,000000,0,0,0,0,1,00,0,0,40,0]])
array([4])



"""# New Section"""